[project]
name = "pypatree"
version = "0.1.0"
description = "Pretty-print a project's module tree"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "setuptools>=75.3.2",
    "tyro>=0.9.35",
]

[project.scripts]
pypatree = "pypatree.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
